module.exports = {
	title: '',
	price: 0,
	seller: '',
	category: '',
	subcategory: '',
	condition: 'new',
	description: '',
	brand: '',
	model: '',
	currency: 'USD',
	recurring_payment: false,
	payment_interval: 'yearly',
	sale: false,
	sale_price: 0,
	in_stock: true,
	sku: '',
	upc: '',
	images: [],
	variations: [],
	tags: [],
	audience: [],
	shipping_prices: []
}
